# Generated by Django 6.0.7 on 2026-07-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0002_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapuser',
            name='bio',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
