# Generated by Django 6.0.7 on 2026-07-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0004_snap_snapreceiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='mode',
            field=models.CharField(choices=[('keep', 'Keep'), ('on_close', 'ON_CLOSE'), ('after_24_hr', 'After_24_hr')], default='keep', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='streak',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
