# Generated by Django 6.0.7 on 2026-07-27 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0006_conversation_updated_at_message_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_snap_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_snap_send',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_snap_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
