# Generated by Django 6.0.7 on 2026-07-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0007_conversation_last_snap_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_snap_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
