# Generated by Codex on 2026-07-29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0008_alter_conversation_last_snap_date'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS snapchat_userlocation (
                            id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                            latitude double precision NOT NULL,
                            longitude double precision NOT NULL,
                            updated_at timestamp with time zone NOT NULL,
                            user_id bigint NOT NULL UNIQUE
                                REFERENCES snapchat_snapuser(id)
                                DEFERRABLE INITIALLY DEFERRED
                        );
                    """,
                    reverse_sql="DROP TABLE IF EXISTS snapchat_userlocation;",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='UserLocation',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('latitude', models.FloatField()),
                        ('longitude', models.FloatField()),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
            ],
        ),
    ]
