# Generated by Django 6.0.7 on 2026-08-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0009_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snapuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
